version: '3.7'
services:
  testproject:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: gunicorn testproject.wsgi --bind=0.0.0.0:8000

    volumes:
      - ./app/:/usr/src/
    ports:
      - 80:8000
    env_file:
      - ./.env