# Generated by Django 4.0.4 on 2022-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
