# Generated by Django 4.0.4 on 2022-04-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tid',
            new_name='id',
        ),
    ]
